version: '3'

services:
  servidor1:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10001:10001"
    networks:
      - chat_network
    depends_on:
      - broker
    command: python /app/Servidor1.py  # Roda diretamente o código do servidor

  servidor2:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "10002:10002"
    networks:
      - chat_network
    depends_on:
      - broker
    command: python /app/Servidor2.py  # Roda diretamente o código do servidor

  broker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    networks:
      - chat_network
    command: python /app/Broker.py  # Roda diretamente o código do broker

networks:
  chat_network:
    driver: bridge
